{{ $userdefault := ((printf "%s@%s" "admin" "localhost")) }}
{{ $host := ((printf "%s.%s.%s.%s.%s" "postgres" (default .Release.Namespace .Values.firezone.namespaceOverride) "svc" "cluster" "local")) }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- (include "firezone.labels" .) | nindent 4 }}
  {{- if .Values.firezone.secret.labels }}
    {{- toYaml .Values.firezone.secret.labels | nindent 4 }}
  {{- end }}     
  name: {{ .Values.firezone.secret.name  | default (include "firezone.name" .) }}
  namespace: {{ include "firezone.namespace" . | quote }}
  {{- if .Values.firezone.secret.annotations }}
  annotations:
    {{- toYaml .Values.firezone.secret.annotations | nindent 4 }}
  {{- end }}   
type: Opaque
{{- if .Values.firezone.secret.data }}
data:
  {{- range $key, $value := .Values.firezone.secret.data }}
  {{ $key }}: {{ $value |b64enc |quote }}
  {{- end }} 
{{- else }}
stringData:
  EXTERNAL_URL: "http://example.host"
  DATABASE_HOST: {{ $host }}
  VERSION: "0.7.26"
  TELEMETRY_ENABLED: "true"
  GUARDIAN_SECRET_KEY: 2FT0UhjAlfiMPnBjUrxMqquouHnTV9DJxAxLDdHnPRhrWTGaj8K3gZMiEdCeHEX0 
  SECRET_KEY_BASE: Z7aSW1iwVRuEiGb1LRopRiAm0pvdvb4+Ip7hAcVpeZnRzl5DztV5O8UN8pSMuEKI
  LIVE_VIEW_SIGNING_SALT: J2j3X5KRz2DUSkCW6aadVy8YFcFuKCXI
  COOKIE_SIGNING_SALT: IJWl3BYP
  COOKIE_ENCRYPTION_SALT: aQ/uhIK/
  DATABASE_ENCRYPTION_KEY: MF65TwOssvHa/AKQNfMEyvFusziYDkbQJMiWj2+mmHU=
  DATABASE_PASSWORD: xxIoJOM3u9Mk4quV 
  WIREGUARD_IPV4_NETWORK: 100.64.0.0/10
  WIREGUARD_IPV4_ADDRESS: 100.64.0.1
  WIREGUARD_IPV6_NETWORK: fd00::/106
  WIREGUARD_IPV6_ADDRESS: fd00::1
  DEFAULT_ADMIN_EMAIL: {{ $userdefault }}
  DEFAULT_ADMIN_PASSWORD: MhrONkM9FpDSInNV 
{{- end }}  
