apiVersion: v1
kind: Service
metadata:
  name: {{ include "firezone.serviceweb.name" . }}-web
  labels:
    {{- include "firezone.labels" . | nindent 4 }}
  namespace: {{ include "firezone.namespace" . | quote }}  
  {{- if .Values.firezone.serviceweb.metadata.annotations }}
  annotations:
    {{- toYaml .Values.firezone.serviceweb.metadata.annotations | nindent 4 }}
  {{- end }}   
spec:
  type: {{ .Values.firezone.serviceweb.type }}
  ports:
    - port: {{ .Values.firezone.serviceweb.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "firezone.selectorLabels" . | nindent 4 }}
