apiVersion: v1
kind: Secret
metadata:
  labels: {{- (include "postgres.labels" .) | nindent 4 }}
  {{- if .Values.postgres.secret.labels }}
    {{- toYaml .Values.postgres.secret.labels | nindent 4 }}
  {{- end }}  
  name: {{ .Values.postgres.secret.name  | default  "postgres"  }}
  namespace: {{ include "firezone.namespace" . | quote }}
  {{- if .Values.postgres.secret.annotations }}  
  annotations:  
    {{- toYaml .Values.postgres.secret.annotations | nindent 4 }}
  {{- end }}   
type: Opaque
stringData:
  PGDATA: /data/postgresql
  POSTGRES_DB: firezone
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.data | default "xxIoJOM3u9Mk4quV" }}
